# pages/ai_assistant.py
#
# Tab 3: AI Sustainability Assistant
#
# What this page does:
#   1. Provides a chat-style interface for asking sustainability questions
#   2. Sends questions to IBM Granite (ibm/granite-3-3-8b-instruct) via watsonx.ai
#   3. Maintains chat history for the current session using st.session_state
#   4. Labels every AI response clearly as AI-generated
#   5. Shows suggested starter questions so students know what to ask
#
# If the text AI is not configured, the page shows a clear "not available" state
# instead of crashing or fabricating responses.

import streamlit as st

from utils.watsonx_client import generate_text, is_text_ai_available
from utils.waste_categories import ASSISTANT_SYSTEM_PROMPT

# A few starter questions displayed as buttons so the user knows what to ask.
# These are purely UI helpers, not special-cased in the AI logic.
STARTER_QUESTIONS = [
    "How should I dispose of a plastic bottle on campus?",
    "What is SDG 12 and why does it matter for students?",
    "How can our college cafeteria reduce food waste?",
    "What is the difference between recyclable and compostable waste?",
    "Why is e-waste dangerous if thrown in a regular bin?",
]

# Session state key for the chat history list
HISTORY_KEY = "assistant_chat_history"


def render() -> None:
    """Main render function called by app.py."""

    st.subheader("🤖 AI Sustainability Assistant")
    st.markdown(
        "Ask any question about campus waste management, recycling, or SDG 12. "
        "Powered by IBM Granite on watsonx.ai."
    )

    # -----------------------------------------------------------------------
    # UNAVAILABLE STATE – shown if credentials are missing
    # -----------------------------------------------------------------------

    if not is_text_ai_available():
        st.warning(
            "**AI Assistant is not configured.**  \n"
            "To enable this feature, add the following to your `.env` file:  \n"
            "```\nWATSONX_API_KEY=your_api_key\n"
            "WATSONX_PROJECT_ID=your_project_id\n```  \n"
            "See `README.md` for step-by-step instructions."
        )
        return

    # -----------------------------------------------------------------------
    # INITIALISE SESSION STATE for chat history
    # -----------------------------------------------------------------------

    if HISTORY_KEY not in st.session_state:
        # Start with a welcome message from the assistant
        st.session_state[HISTORY_KEY] = [
            {
                "role": "assistant",
                "content": (
                    "Hello! I'm EcoTrack AI, your campus sustainability assistant. "
                    "I can help you understand waste segregation, recycling practices, "
                    "and SDG 12. What would you like to know?"
                ),
            }
        ]

    # -----------------------------------------------------------------------
    # STARTER QUESTIONS – shown as clickable buttons
    # -----------------------------------------------------------------------

    st.markdown("**💡 Try asking:**")
    cols = st.columns(len(STARTER_QUESTIONS))
    for i, question in enumerate(STARTER_QUESTIONS):
        with cols[i]:
            if st.button(question, key=f"starter_{i}", use_container_width=True):
                # Treat a button click exactly like a typed message
                st.session_state["_pending_message"] = question

    st.divider()

    # -----------------------------------------------------------------------
    # CHAT HISTORY DISPLAY
    # -----------------------------------------------------------------------

    for message in st.session_state[HISTORY_KEY]:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])
            # Label every AI response
            if message["role"] == "assistant" and message["content"].startswith("Hello!") is False:
                st.caption(
                    "🤖 Generated by IBM Granite (ibm/granite-3-3-8b-instruct) via watsonx.ai. "
                    "AI can make mistakes – verify important facts independently."
                )

    # -----------------------------------------------------------------------
    # HANDLE PENDING MESSAGE (from starter button click)
    # -----------------------------------------------------------------------

    pending = st.session_state.pop("_pending_message", None)

    # -----------------------------------------------------------------------
    # CHAT INPUT
    # -----------------------------------------------------------------------

    user_input = st.chat_input(
        "Ask a sustainability question...",
        key="assistant_input",
    )

    # Use pending message from button OR typed input
    user_message = pending or user_input

    if user_message:
        # Add user message to history
        st.session_state[HISTORY_KEY].append(
            {"role": "user", "content": user_message}
        )

        # Display user message immediately
        with st.chat_message("user"):
            st.markdown(user_message)

        # Build context from the last 6 messages (3 turns) to keep the prompt short
        # We do NOT send the full history to avoid exceeding token limits
        recent_turns = st.session_state[HISTORY_KEY][-6:]
        context_text = "\n".join(
            f"{'User' if m['role'] == 'user' else 'Assistant'}: {m['content']}"
            for m in recent_turns[:-1]   # exclude the message we just added
        )

        if context_text:
            full_prompt = (
                f"Previous conversation:\n{context_text}\n\n"
                f"User: {user_message}"
            )
        else:
            full_prompt = user_message

        # Call the AI
        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                response, error = generate_text(
                    prompt=full_prompt,
                    system_prompt=ASSISTANT_SYSTEM_PROMPT,
                    max_new_tokens=512,
                )

            if error:
                error_msg = (
                    f"Sorry, I could not generate a response right now. "
                    f"Error: {error}"
                )
                st.error(error_msg)
                st.session_state[HISTORY_KEY].append(
                    {"role": "assistant", "content": error_msg}
                )
            else:
                st.markdown(response)
                st.caption(
                    "🤖 Generated by IBM Granite (ibm/granite-3-3-8b-instruct) via watsonx.ai. "
                    "AI can make mistakes – verify important facts independently."
                )
                st.session_state[HISTORY_KEY].append(
                    {"role": "assistant", "content": response}
                )

    # -----------------------------------------------------------------------
    # CLEAR HISTORY BUTTON
    # -----------------------------------------------------------------------

    st.divider()
    if st.button("🗑️ Clear chat history"):
        st.session_state.pop(HISTORY_KEY, None)
        st.rerun()
